# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
