# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170403_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255)),
                ('acao', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='acao',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='operacao',
            name='periodo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operacao',
            name='serie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
