# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170404_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='serie_id',
            new_name='titulo_id',
        ),
    ]
