# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170404_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
