# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170404_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='quantidade',
            new_name='valor',
        ),
    ]
